version: '3'
services:
  gocd-server:
    image: gocd/gocd-server:v18.2.0
    environment:
     - AGENT_AUTO_REGISTER_KEY=c53fcbb4-0f35-49bc-8186-b3272d15d6ff
    ports:
     - 8153:8153
     - 8154:8154
    volumes:
     - ./gocd-server-data:/godata
     - ./gocd-server-home:/home/go
  gocd-agent-default:
    image: gocd/gocd-agent-ubuntu-16.04:v18.2.0
    environment:
     - GO_SERVER_URL=https://gocd-server:8154/go
     - AGENT_AUTO_REGISTER_KEY=c53fcbb4-0f35-49bc-8186-b3272d15d6ff
     - AGENT_AUTO_REGISTER_RESOURCES=default,linux,java,jre
     - AGENT_AUTO_REGISTER_ENVIRONMENTS=Build,Demo,Prod
     - AGENT_AUTO_REGISTER_HOSTNAME=Ubuntu Agent
    depends_on:
     - gocd-server
    restart: always
  gocd-agent-jdk:
    build:
      context: .
      dockerfile: Dockerfile.agent-jdk
    environment:
     - GO_SERVER_URL=https://gocd-server:8154/go
     - AGENT_AUTO_REGISTER_KEY=c53fcbb4-0f35-49bc-8186-b3272d15d6ff
     - AGENT_AUTO_REGISTER_RESOURCES=linux,java,jre,jdk
     - AGENT_AUTO_REGISTER_ENVIRONMENTS=Build,Demo
     - AGENT_AUTO_REGISTER_HOSTNAME=Ubuntu JDK Agent
    depends_on:
      - gocd-server
    restart: always
  gocd-agent-npm:
    build:
      context: .
      dockerfile: Dockerfile.agent-npm
    environment:
     - GO_SERVER_URL=https://gocd-server:8154/go
     - AGENT_AUTO_REGISTER_KEY=c53fcbb4-0f35-49bc-8186-b3272d15d6ff
     - AGENT_AUTO_REGISTER_RESOURCES=linux,node,npm,nvm
     - AGENT_AUTO_REGISTER_ENVIRONMENTS=Build,Demo
     - AGENT_AUTO_REGISTER_HOSTNAME=Ubuntu NodeJS Agent
    depends_on:
      - gocd-server
    restart: always
  gocd-agent-golang:
    build:
      context: .
      dockerfile: Dockerfile.agent-golang
    environment:
     - GO_SERVER_URL=https://gocd-server:8154/go
     - AGENT_AUTO_REGISTER_KEY=c53fcbb4-0f35-49bc-8186-b3272d15d6ff
     - AGENT_AUTO_REGISTER_RESOURCES=linux,golang,go
     - AGENT_AUTO_REGISTER_ENVIRONMENTS=Build,Demo
     - AGENT_AUTO_REGISTER_HOSTNAME=Ubuntu Golang Agent
    depends_on:
      - gocd-server
    restart: always
  webserver:
    container_name: webserver1
    build:
      context: .
      dockerfile: Dockerfile.webserver
    restart: always
    ports:
     - 22:22
