version: '3'
services:
  gocd-server:
    image: gocd/gocd-server:v17.12.0
    environment:
     - AGENT_AUTO_REGISTER_KEY=51684b3d-a40f-4ef0-8003-d239a3125aed
    ports:
     - 8153:8153
     - 8154:8154
    volumes:
     - ./gocd-server-data:/godata
     - ./gocd-server-home:/home/go
  gocd-agent-default:
    image: gocd/gocd-agent-ubuntu-16.04:v17.12.0
    environment:
     - GO_SERVER_URL=https://gocd-server:8154/go
     - AGENT_AUTO_REGISTER_KEY=51684b3d-a40f-4ef0-8003-d239a3125aed
     - AGENT_AUTO_REGISTER_RESOURCES=default,linux,java,jre
    depends_on:
     - gocd-server
    restart: always
  gocd-agent-jdk:
    build:
      context: .
      dockerfile: Dockerfile.agent-jdk
    environment:
     - GO_SERVER_URL=https://gocd-server:8154/go
     - AGENT_AUTO_REGISTER_KEY=51684b3d-a40f-4ef0-8003-d239a3125aed
     - AGENT_AUTO_REGISTER_RESOURCES=linux,java,jre,jdk
    depends_on:
      - gocd-server
    restart: always
  gocd-agent-npm:
    build:
      context: .
      dockerfile: Dockerfile.agent-npm
    environment:
     - GO_SERVER_URL=https://gocd-server:8154/go
     - AGENT_AUTO_REGISTER_KEY=51684b3d-a40f-4ef0-8003-d239a3125aed
     - AGENT_AUTO_REGISTER_RESOURCES=linux,node,npm,nvm
    depends_on:
      - gocd-server
    restart: always
  gocd-agent-golang:
    build:
      context: .
      dockerfile: Dockerfile.agent-golang
    environment:
     - GO_SERVER_URL=https://gocd-server:8154/go
     - AGENT_AUTO_REGISTER_KEY=51684b3d-a40f-4ef0-8003-d239a3125aed
     - AGENT_AUTO_REGISTER_RESOURCES=linux,golang,go
    depends_on:
      - gocd-server
    restart: always
  webserver:
    container_name: webserver1
    build:
      context: .
      dockerfile: Dockerfile.webserver
    command: sleep infinity
    restart: always
